// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Data;

#nullable disable

namespace UserManagement.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230627131944_Initial-Setup")]
    partial class InitialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("AuditLogs", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("UserManagement.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateOfBirth = new DateTime(1992, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ploew@example.com",
                            Forename = "Peter",
                            IsActive = true,
                            Surname = "Loew"
                        },
                        new
                        {
                            Id = 2L,
                            DateOfBirth = new DateTime(1995, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bfgates@example.com",
                            Forename = "Benjamin Franklin",
                            IsActive = true,
                            Surname = "Gates"
                        },
                        new
                        {
                            Id = 3L,
                            DateOfBirth = new DateTime(1997, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ctroy@example.com",
                            Forename = "Castor",
                            IsActive = false,
                            Surname = "Troy"
                        },
                        new
                        {
                            Id = 4L,
                            DateOfBirth = new DateTime(1998, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mraines@example.com",
                            Forename = "Memphis",
                            IsActive = true,
                            Surname = "Raines"
                        },
                        new
                        {
                            Id = 5L,
                            DateOfBirth = new DateTime(1999, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sgodspeed@example.com",
                            Forename = "Stanley",
                            IsActive = true,
                            Surname = "Goodspeed"
                        },
                        new
                        {
                            Id = 6L,
                            DateOfBirth = new DateTime(1996, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "himcdunnough@example.com",
                            Forename = "H.I.",
                            IsActive = true,
                            Surname = "McDunnough"
                        },
                        new
                        {
                            Id = 7L,
                            DateOfBirth = new DateTime(1997, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cpoe@example.com",
                            Forename = "Cameron",
                            IsActive = false,
                            Surname = "Poe"
                        },
                        new
                        {
                            Id = 8L,
                            DateOfBirth = new DateTime(1993, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emalus@example.com",
                            Forename = "Edward",
                            IsActive = false,
                            Surname = "Malus"
                        },
                        new
                        {
                            Id = 9L,
                            DateOfBirth = new DateTime(1995, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dmacready@example.com",
                            Forename = "Damon",
                            IsActive = false,
                            Surname = "Macready"
                        },
                        new
                        {
                            Id = 10L,
                            DateOfBirth = new DateTime(1999, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jblaze@example.com",
                            Forename = "Johnny",
                            IsActive = true,
                            Surname = "Blaze"
                        },
                        new
                        {
                            Id = 11L,
                            DateOfBirth = new DateTime(1999, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rfeld@example.com",
                            Forename = "Robin",
                            IsActive = true,
                            Surname = "Feld"
                        });
                });

            modelBuilder.Entity("AuditLogs", b =>
                {
                    b.HasOne("UserManagement.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserManagement.Models.User", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
